// 클러스터 스타일
export const clusterStyle = {
  region: [
    {
      display: "inline-flex",
      padding: "12px 34px",
      justifyContent: "center",
      alignItems: "center",
      gap: "10px",
      borderRadius: "119px",
      border: "2px solid #39b94c",
      background: "#F8F9FB",
      boxShadow: "0px 0px 20px 0px rgba(0, 0, 0, 0.08)",
    },
  ],
  number: [
    {
      display: "flex",
      width: "108px",
      height: "108px",
      padding: "33.987px 45.316px",
      flexDirection: "column",
      justifyContent: "center",
      alignItems: "center",
      borderRadius: "54.521px",
      background: "rgba(57, 185, 76, 0.78)",
      color: "#FFF",
      textAlign: "center",
      fontSize: "24px",
      fontWeight: "700",
    },
    {
      display: "flex",
      width: "130px",
      height: "130px",
      padding: "41.872px 55.83px",
      flexDirection: "column",
      justifyContent: "center",
      alignItems: "center",
      borderRadius: "67.17px",
      background: "rgba(57, 185, 76, 0.78)",
      color: "#FFF",
      textAlign: "center",
      fontSize: "24px",
      fontWeight: "700",
    },
    {
      display: "flex",
      width: "156px",
      height: "156px",
      padding: "51.117px 68.156px",
      flexDirection: "column",
      justifyContent: "center",
      alignItems: "center",
      borderRadius: "82px",
      background: "rgba(57, 185, 76, 0.78)",
      color: "#FFF",
      textAlign: "center",
      fontSize: "24px",
      fontWeight: "700",
    },
  ],
};
